HamburgerciUygulamasi.UI/Areas/AdminArea/Controllers/ExtraController.cs
using AutoMapper;
using HamburgerciUygulamasi.BLL.Services.Interfaces;
using HamburgerciUygulamasi.DAL.Entities.Concrete;
using HamburgerciUygulamasi.DAL.Enums;
using HamburgerciUygulamasi.UI.Areas.AdminArea.Models.VM;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Hosting;

namespace HamburgerciUygulamasi.UI.Areas.AdminArea.Controllers
{
    [Authorize(Roles = "admin")]
    [Area("AdminArea")]
    public class ExtraController : Controller
    {
        IExtraService extraService;
        IMapper mapper;
        public ExtraController(IExtraService service, IMapper mapper)
        {
            extraService = service;
            this.mapper = mapper;
        }
        public IActionResult Index(ExtraIndexVM vm)
        {

            List<Extra> extras;

            if (vm.IsEnter.HasValue)
            {
                if (!string.IsNullOrWhiteSpace(vm.Name))
                {
                    extras = extraService.GetBy(x => x.Name.Contains(vm.Name) && x.Status == Status.Active).ToList();
                    return View(vm);
                }
            }

            vm = new ExtraIndexVM();
            extras = extraService.GetBy(x => x.Status == Status.Active).ToList();
            vm.Extras = mapper.Map<List<ExtraIndexItem>>(extras);
            return View(vm);
        }
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Add(ExtraAddVM vm)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Extra extra = mapper.Map<Extra>(vm);

                    extra.Status = Status.Active;
                    extra.CreatedDate = DateTime.Now;

                    using (MemoryStream ms = new MemoryStream())
                    {
                        vm.Picture_.CopyTo(ms);
                        extra.Picture = ms.ToArray();
                    }

                    extraService.Add(extra);

                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {

                }
            }
            TempData["message"] = $"Bir Hata Oluştu";
            return View();
        }
        [HttpGet]
        public IActionResult Edit(Guid id)
        {
            Extra extra = extraService.Find(id);
            ExtraEditVM vm = mapper.Map<ExtraEditVM>(extra);
            
            return View(vm);
        }
        [HttpPost]
        public IActionResult Edit(ExtraEditVM vm)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var extra = extraService.Find(vm.Id);
                    extra = mapper.Map(vm, extra);
                    if (vm.Picture_ != null && vm.Picture_.Length > 0)
                    {
                        using (MemoryStream ms = new MemoryStream())
                        {
                            vm.Picture_.CopyTo(ms);
                            extra.Picture = ms.ToArray();
                        }
                    }
                    extraService.Edit(extra);
                    
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {

                }
            }
            TempData["message"] = $"Bir Hata Oluştu";
            return View();
        }
        public IActionResult Remove(Guid id)
        {
            try
            {
                Extra extra = extraService.Find(id);
                extraService.Remove(extra);
            }
            catch (Exception)
            {

            }
            return RedirectToAction("Index");
        }

    }
}

HamburgerciUygulamasi.UI/Areas/AdminArea/Controllers/MenuController.cs
using AutoMapper;
using HamburgerciUygulamasi.BLL.Services.Concretes;
using HamburgerciUygulamasi.BLL.Services.Interfaces;
using HamburgerciUygulamasi.DAL.Entities.Concrete;
using HamburgerciUygulamasi.DAL.Enums;
using HamburgerciUygulamasi.UI.Areas.AdminArea.Models.VM;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HamburgerciUygulamasi.UI.Areas.AdminArea.Controllers
{
    [Authorize(Roles = "admin")]
    [Area("AdminArea")]
    public class MenuController : Controller
    {
        IMenuService menuService;
        IMapper mapper;
        public MenuController(IMenuService service, IMapper mapper)
        {
            menuService = service;
            this.mapper = mapper;
        }
        public IActionResult Index(MenuIndexVM vm)
        {
            List<Menu> menus;

            if (vm.IsEnter.HasValue)
            {
                if (!string.IsNullOrWhiteSpace(vm.Name))
                {
                    menus = menuService.GetBy(x => x.Name.Contains(vm.Name) && x.Status == Status.Active).ToList();
                    return View(vm);
                }
            }

            vm = new MenuIndexVM();
            menus = menuService.GetBy(x => x.Status == Status.Active).ToList();
            vm.Menus = mapper.Map<List<MenuIndexItem>>(menus);
            return View(vm);
        }
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Add(MenuAddVM vm)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Menu menu = mapper.Map<Menu>(vm);

                    menu.Status = Status.Active;
                    menu.CreatedDate = DateTime.Now;

                    using (MemoryStream ms = new MemoryStream())
                    {
                        vm.Picture_.CopyTo(ms);
                        menu.Picture = ms.ToArray();
                    }

                    menuService.Add(menu);

                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {

                }
            }
            TempData["message"] = $"Bir Hata Oluştu";
            return View();
        }
        [HttpGet]
        public IActionResult Edit(Guid id)
        {
            Menu menu = menuService.Find(id);
            MenuEditVM vm = mapper.Map<MenuEditVM>(menu);

            return View(vm);
        }
        [HttpPost]
        public IActionResult Edit(MenuEditVM vm)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var menu = menuService.Find(vm.Id);
                    menu = mapper.Map(vm, menu);
                    if (vm.Picture_ != null && vm.Picture_.Length > 0)
                    {
                        using (MemoryStream ms = new MemoryStream())
                        {
                            vm.Picture_.CopyTo(ms);
                            menu.Picture = ms.ToArray();
                        }
                    }
                    menuService.Edit(menu);

                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {

                }
            }
            TempData["message"] = $"Bir Hata Oluştu";
            return View();
        }
        public IActionResult Remove(Guid id)
        {
            try
            {
                Menu menu = menuService.Find(id);
                menuService.Remove(menu);
            }
            catch (Exception)
            {

            }
            return RedirectToAction("Index");
        }
    }
}

HamburgerciUygulamasi.UI/Areas/AdminArea/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta name="description" content="Miminium Admin Template v.1">
    <meta name="author" content="Isna Nur Azis">
    <meta name="keyword" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hamburger</title>

    <!-- start: Css -->
    <link rel="stylesheet" type="text/css" href="~/asset/css/bootstrap.min.css">

    <!-- plugins -->
    <link rel="stylesheet" type="text/css" href="~/asset/css/plugins/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="~/asset/css/plugins/datatables.bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="~/asset/css/plugins/animate.min.css" />
    <link href="~/asset/css/style.css" rel="stylesheet">
    <!-- end: Css -->

    <link rel="shortcut icon" href="~/asset/img/logomi.png">
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
      <![endif]-->
</head>

<body id="mimin" class="dashboard">
    <!-- start: Header -->
    <nav class="navbar navbar-default header navbar-fixed-top">
        <div class="col-md-12 nav-wrapper">
            <div class="navbar-header" style="width:100%;">
                
                <a class="navbar-brand">
                    <b>Hamburger</b>
                </a>

                <ul class="nav navbar-nav navbar-right user-nav">
                    <li><a href="@Url.Action("SignOut", "Account", new { area = "" })">SignOut</a></li>
                    <li class="user-name"><span>@ViewData["UserName"]</span></li>
                    <li class="dropdown avatar-dropdown">
                        <img src="~/asset/img/avatar.jpg" class="img-circle avatar" alt="user name" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" />
                </ul>
            </div>
        </div>
    </nav>
    <!-- end: Header -->

    <div class="container-fluid mimin-wrapper">
        <!-- start:Left Menu -->
        <div id="left-menu">
            <div class="sub-left-menu scroll">
                <ul class="nav nav-list">
                    <li><div class="left-bg"></div></li>
                    <li class="time">
                        <h1 class="animated fadeInLeft">21:00</h1>
                        <p class="animated fadeInRight">Sat,October 1st 2029</p>
                    </li>

                    <li><a href="@Url.Action("Index", "Menu", new { area = "AdminArea" })">Menu</a></li>
                    <li><a href="@Url.Action("Index", "Extra", new { area = "AdminArea" })">Extra</a></li>
                    

                </ul>
            </div>
        </div>
        <!-- end: Left Menu -->

        @RenderBody()


    </div>

    <!-- start: Mobile -->
    <div id="mimin-mobile" class="reverse">
        <div class="mimin-mobile-menu-list">
            <div class="col-md-12 sub-mimin-mobile-menu-list animated fadeInLeft">
                <ul class="nav nav-list">
                    <li class="active ripple">
                        <a class="tree-toggle nav-header">
                            <span class="fa-home fa"></span>Dashboard
                            <span class="fa-angle-right fa right-arrow text-right"></span>
                        </a>
                        <ul class="nav nav-list tree">
                            <li><a href="dashboard-v1.html">Dashboard v.1</a></li>
                            <li><a href="dashboard-v2.html">Dashboard v.2</a></li>
                        </ul>
                    </li>
                    <li class="ripple">
                        <a class="tree-toggle nav-header">
                            <span class="fa-diamond fa"></span>Layout
                            <span class="fa-angle-right fa right-arrow text-right"></span>
                        </a>
                        <ul class="nav nav-list tree">
                            <li><a href="topnav.html">Top Navigation</a></li>
                            <li><a href="boxed.html">Boxed</a></li>
                        </ul>
                    </li>
                    <li class="ripple">
                        <a class="tree-toggle nav-header">
                            <span class="fa-area-chart fa"></span>Charts
                            <span class="fa-angle-right fa right-arrow text-right"></span>
                        </a>
                        <ul class="nav nav-list tree">
                            <li><a href="chartjs.html">ChartJs</a></li>
                            <li><a href="morris.html">Morris</a></li>
                            <li><a href="flot.html">Flot</a></li>
                            <li><a href="sparkline.html">SparkLine</a></li>
                        </ul>
                    </li>
                    <li class="ripple">
                        <a class="tree-toggle nav-header">
                            <span class="fa fa-pencil-square"></span>Ui Elements
                            <span class="fa-angle-right fa right-arrow text-right"></span>
                        </a>
                        <ul class="nav nav-list tree">
                            <li><a href="color.html">Color</a></li>
                            <li><a href="weather.html">Weather</a></li>
                            <li><a href="typography.html">Typography</a></li>
                            <li><a href="icons.html">Icons</a></li>
                            <li><a href="buttons.html">Buttons</a></li>
                            <li><a href="media.html">Media</a></li>
                            <li><a href="panels.html">Panels & Tabs</a></li>
                            <li><a href="notifications.html">Notifications & Tooltip</a></li>
                            <li><a href="badges.html">Badges & Label</a></li>
                            <li><a href="progress.html">Progress</a></li>
                            <li><a href="sliders.html">Sliders</a></li>
                            <li><a href="timeline.html">Timeline</a></li>
                            <li><a href="modal.html">Modals</a></li>
                        </ul>
                    </li>
                    <li class="ripple">
                        <a class="tree-toggle nav-header">
                            <span class="fa fa-check-square-o"></span>Forms
                            <span class="fa-angle-right fa right-arrow text-right"></span>
                        </a>
                        <ul class="nav nav-list tree">
                            <li><a href="formelement.html">Form Element</a></li>
                            <li><a href="#">Wizard</a></li>
                            <li><a href="#">File Upload</a></li>
                            <li><a href="#">Text Editor</a></li>
                        </ul>
                    </li>
                    <li class="ripple">
                        <a class="tree-toggle nav-header">
                            <span class="fa fa-table"></span>Tables
                            <span class="fa-angle-right fa right-arrow text-right"></span>
                        </a>
                        <ul class="nav nav-list tree">
                            <li><a href="datatables.html">Data Tables</a></li>
                            <li><a href="handsontable.html">handsontable</a></li>
                            <li><a href="tablestatic.html">Static</a></li>
                        </ul>
                    </li>
                    <li class="ripple">
                        <a href="calendar.html">
                            <span class="fa fa-calendar-o"></span>Calendar
                        </a>
                    </li>
                    <li class="ripple">
                        <a class="tree-toggle nav-header">
                            <span class="fa fa-envelope-o"></span>Mail
                            <span class="fa-angle-right fa right-arrow text-right"></span>
                        </a>
                        <ul class="nav nav-list tree">
                            <li><a href="mail-box.html">Inbox</a></li>
                            <li><a href="compose-mail.html">Compose Mail</a></li>
                            <li><a href="view-mail.html">View Mail</a></li>
                        </ul>
                    </li>
                    <li class="ripple">
                        <a class="tree-toggle nav-header">
                            <span class="fa fa-file-code-o"></span>Pages
                            <span class="fa-angle-right fa right-arrow text-right"></span>
                        </a>
                        <ul class="nav nav-list tree">
                            <li><a href="forgotpass.html">Forgot Password</a></li>
                            <li><a href="login.html">SignIn</a></li>
                            <li><a href="reg.html">SignUp</a></li>
                            <li><a href="article-v1.html">Article v1</a></li>
                            <li><a href="search-v1.html">Search Result v1</a></li>
                            <li><a href="productgrid.html">Product Grid</a></li>
                            <li><a href="profile-v1.html">Profile v1</a></li>
                            <li><a href="invoice-v1.html">Invoice v1</a></li>
                        </ul>
                    </li>
                    <li class="ripple">
                        <a class="tree-toggle nav-header"><span class="fa "></span> MultiLevel  <span class="fa-angle-right fa right-arrow text-right"></span> </a>
                        <ul class="nav nav-list tree">
                            <li><a href="view-mail.html">Level 1</a></li>
                            <li><a href="view-mail.html">Level 1</a></li>
                            <li class="ripple">
                                <a class="sub-tree-toggle nav-header">
                                    <span class="fa fa-envelope-o"></span> Level 1
                                    <span class="fa-angle-right fa right-arrow text-right"></span>
                                </a>
                                <ul class="nav nav-list sub-tree">
                                    <li><a href="mail-box.html">Level 2</a></li>
                                    <li><a href="compose-mail.html">Level 2</a></li>
                                    <li><a href="view-mail.html">Level 2</a></li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                    <li><a href="credits.html">Credits</a></li>
                </ul>
            </div>
        </div>
    </div>
    <button id="mimin-mobile-menu-opener" class="animated rubberBand btn btn-circle btn-danger">
        <span class="fa fa-bars"></span>
    </button>
    <!-- end: Mobile -->
    <!-- start: Javascript -->
    <script src="~/asset/js/jquery.min.js"></script>
    <script src="~/asset/js/jquery.ui.min.js"></script>
    <script src="~/asset/js/bootstrap.min.js"></script>



    <!-- plugins -->
    <script src="~/asset/js/plugins/moment.min.js"></script>
    <script src="~/asset/js/plugins/jquery.datatables.min.js"></script>
    <script src="~/asset/js/plugins/datatables.bootstrap.min.js"></script>
    <script src="~/asset/js/plugins/jquery.nicescroll.js"></script>


    <!-- custom -->
    <script src="~/asset/js/main.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#datatables-example').DataTable();
        });
    </script>
    <!-- end: Javascript -->
</body>
</html>